schema_version: 1

context:
  name: fricas
  version: 1.3.12

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/fricas/fricas/releases/download/${{ version }}/fricas-${{ version }}-full.tar.bz2
  sha256: 33201f9f56c20b1266d38f5290efe7486a38422ea90f707f0345f6a589e31c8d

build:
  # Windows builds seem to only work with Cygwin
  # building on macOS fails with strange errors about zstd which seem to be related to some build/host directory confusion. It will be easier to figure this out once this is in the feedstock.
  number: 1
  skip: win or osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - sbcl
    - zstd

tests:
  - script:
      - fricas -nox -eval ")qu"

about:
  summary: an advanced computer algebra system
  description: |
    FriCAS is an advanced computer algebra system. Its capabilities range from
    calculus (integration and differentiation) to abstract algebra. It can plot
    functions and has integrated help system.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://fricas.org
  repository: https://groups.google.com/g/fricas-devel
  documentation: https://fricas.org/index0.html

extra:
  recipe-maintainers:
    - mantepse
    - saraedum

